/*
 * This source file was generated by the Gradle 'init' task
 */
package booking;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class App {

    public static void main(String[] args) {

        List<Integer> list = Arrays.asList(1,2,3,4,5,6);
        list.stream().map(e->e*2).collect(Collectors.toList());


    }
}
